{"id_": "1339698808574398465", "raw_data": {"created_at": "Thu Dec 17 22:27:41 +0000 2020", "id": 1339698808574398465, "id_str": "1339698808574398465", "full_text": "Datenschutz ist nicht Problem der #Corona-App.\nNur jede Phantasielosigkeit als Datenschutzproblem auszugeben ist inakzeptabel.\nAusschließliche Verwendung der App-Daten für Pandemieeindämmungszwecke &amp; ggf. die Freigabe durch Dateninhaber*innen widerspricht dem Datenschutz nicht.", "truncated": false, "display_text_range": [0, 282], "entities": {"hashtags": [{"text": "Corona", "indices": [34, 41]}], "symbols": [], "user_mentions": [], "urls": []}, "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>", "in_reply_to_status_id": null, "in_reply_to_status_id_str": null, "in_reply_to_user_id": null, "in_reply_to_user_id_str": null, "in_reply_to_screen_name": null, "user_id": 16337664, "user_id_str": "16337664", "geo": null, "coordinates": null, "place": null, "contributors": null, "is_quote_status": false, "retweet_count": 2, "favorite_count": 19, "reply_count": 1, "quote_count": 0, "conversation_id": 1339698808574398465, "conversation_id_str": "1339698808574398465", "favorited": false, "retweeted": false, "lang": "de", "supplemental_language": null}}